version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/results:/app/results
    environment:
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
